### PR TITLE
adding email and phone number to tool

### PR DESCRIPTION
**Pull request by ekraihan**
My solution for the search stored proc not returning email is not pretty. I was thinking that in reality, phone, email, and username are not even part of a tool, so maybe they don't belong in my Tool class. I'll address that issue later. The code here should work.

### CODE REVIEW

**Comment by JerebChase** [comment]
I can make the search stored proc return email and phonenumber easily if that would be good?

**Comment by ekraihan** [comment]
That would work Jere. But if NOT returning as many values with the search proc will make the search page load faster , that may be better. We can talk 

- Elias Kraihanzel

**Comment by Jbcampbe** [comment]
What do you think about going for features first and worrying about speed second @ekraihan ? If we have lag issues we can look into performance improvements in a later hotfix/release

**Comment by ekraihan** [comment]
Fine by me Josiah. 

But Jere, you wouldn't have to add more fields to the search return values. We currently are returning 10 fields. Addding two more would slow down the search page by 16.66%. But if speed isn't much of a concern, I'm fine with it :)

- Elias Kraihanzel

**Comment by Jbcampbe** [comment]
If you feel strongly chip that it is going to create a noticeably slower UI to have 2 extra fields than we certainly take measures to avoid it... I guess I wasn't thinking that 2 fields would have that much of an affect.

Also I don't think we can just say 2/12 means that we are adding 16.6% of the Entire search query. You may or may not have been kidding but if you weren't I'm going to cite Amdahl's Law ?
_____________________________

**Pull request merged**
